
name: Verify Tag
run-name: verify-tag

on:
  push: 
    branches: 
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          TAG="$(jq -r .version package.json)"
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            core.setFailed("Tag ${TAG} exists. Kindly update the version")
          fi
      - run: npm install
      - run: npm test
