name: Create Release on PR Merge to Master

on:
  pull_request: 
    branches: master
    types: [closed]

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Run Tests
        run: npm test

      - name: Build the project
        run: npm run build

      - name: Create a tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create a .tgz package
        run: |
          # npm pack --pack-destination ./lib
          tar -czvf ${{ env.PACKAGE_NAME }}-v${{ env.VERSION }}.tgz -C lib .

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PACKAGE_NAME }}-v${{ env.VERSION }}.tgz
          asset_name:  ${{ env.PACKAGE_NAME }}-v${{ env.VERSION }}.tgz
          tag: v${{ env.VERSION }}
          overwrite: true
          body: "${{ env.ASSET_NAME }} ${{ env.VERSION }}"
